// Writes out/_headers, which Cloudflare applies to the static files it serves.
//
// The Content-Security-Policy is built from the actual build output: Next.js puts small
// inline scripts in every exported page, so the policy lists the hash of each one.
// Nothing inline is allowed that this build did not produce, and 'unsafe-inline' is
// never needed for scripts.
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import nextEnv from "@next/env";

nextEnv.loadEnvConfig(process.cwd(), false);

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "out");

// Cloudflare limits: 2,000 characters per header line, 100 rules per file.
const MAX_LINE = 2000;
const MAX_RULES = 100;

const analytics = Boolean(process.env.NEXT_PUBLIC_CF_ANALYTICS_TOKEN);
const TURNSTILE = "https://challenges.cloudflare.com";

async function listHtml(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await listHtml(full)));
    else if (entry.name.endsWith(".html")) files.push(full);
  }
  return files;
}

// out/index.html -> "/", out/about.html -> "/about", out/a/index.html -> "/a"
function routeFor(file) {
  const relative = path.relative(outDir, file).split(path.sep).join("/");
  const route = "/" + relative.replace(/\.html$/, "").replace(/(^|\/)index$/, "");
  return route.length > 1 ? route.replace(/\/$/, "") : "/";
}

function inlineScriptHashes(html) {
  const hashes = new Set();
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const [, attributes, body] = match;
    if (/\bsrc\s*=/.test(attributes) || body.length === 0) continue;
    // Data blocks such as JSON-LD are not executed, so the policy does not apply to them.
    const type = /\btype\s*=\s*["']?([^"'\s>]+)/i.exec(attributes)?.[1]?.toLowerCase();
    if (type && type !== "module" && !type.includes("javascript")) continue;
    hashes.add(`'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`);
  }
  return [...hashes];
}

function policy(hashes) {
  const directives = [
    "default-src 'self'",
    ["script-src 'self'", ...hashes, TURNSTILE, analytics ? "https://static.cloudflareinsights.com" : ""],
    // Inline style attributes carry animation delays; they cannot run code.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    ["connect-src 'self'", TURNSTILE, analytics ? "https://cloudflareinsights.com" : ""],
    `frame-src ${TURNSTILE}`,
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    "upgrade-insecure-requests",
  ];
  return directives.map((d) => (Array.isArray(d) ? d.filter(Boolean).join(" ") : d)).join("; ");
}

const pages = [];
for (const file of (await listHtml(outDir)).sort()) {
  pages.push({ route: routeFor(file), hashes: inlineScriptHashes(await readFile(file, "utf8")) });
}

const lines = [
  "# Generated by scripts/generate-headers.mjs on every build. Do not edit by hand.",
  "",
  "/*",
  "  X-Content-Type-Options: nosniff",
  "  X-Frame-Options: DENY",
  "  Referrer-Policy: strict-origin-when-cross-origin",
  "  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()",
  "  Strict-Transport-Security: max-age=31536000; includeSubDomains",
  "  Cross-Origin-Opener-Policy: same-origin",
  "",
  "/_next/static/*",
  "  Cache-Control: public, max-age=31536000, immutable",
  "",
  // Safe to cache for a year: each image URL carries a hash of its source photo.
  "/images/*",
  "  Cache-Control: public, max-age=31536000, immutable",
  "",
];

// Preferred: one policy on the catch-all rule, listing every page's inline scripts. It
// covers every response, including the 404 page served for unknown addresses.
// Fallback when that line would be too long: one rule per page. A header set by two
// matching rules is sent twice and both policies are enforced, so the two forms are
// never mixed. In the fallback, the 404 page for unknown addresses has no policy.
const combined = `  Content-Security-Policy: ${policy([...new Set(pages.flatMap((page) => page.hashes))])}`;
if (combined.length <= MAX_LINE) {
  lines.splice(lines.indexOf("/*") + 1, 0, combined);
} else {
  console.warn("[headers] Combined policy is too long for one line; writing one policy per page instead.");
  for (const { route, hashes } of pages) {
    const line = `  Content-Security-Policy: ${policy(hashes)}`;
    if (line.length > MAX_LINE) {
      throw new Error(`The policy for ${route} is ${line.length} characters; Cloudflare allows ${MAX_LINE}.`);
    }
    lines.push(route, line, "");
  }
}

const ruleCount = lines.filter((line) => line.startsWith("/")).length;
if (ruleCount > MAX_RULES) throw new Error(`${ruleCount} header rules; Cloudflare allows ${MAX_RULES}.`);

await writeFile(path.join(outDir, "_headers"), lines.join("\n"));
console.log(`[headers] Wrote out/_headers: ${ruleCount} rules, policy built from ${pages.length} pages.`);
